#!/bin/sh

# Drop the "--" argument if present.
# Ranger passes "--" to indicate the end of the arguments, but vim treats it
# as a filename after the --remote family of arguments.
if [ "$1" == "--" ]; then
  shift
fi

# Exit if we don't know what server/session to use
if [ -z "$VRIM_ID" ]; then
  echo "VRIM_ID not set!" >&2
  echo "vrim is not meant to be invoked directly" >&2
  exit 1
fi

# Exit if we don't have a DETACH mapping
if [ -z "$DETACH" ]; then
  echo "DETACH not set!" >&2
  echo "vrim is not meant to be invoked directly" >&2
  exit 1
fi

REMAP="nnoremap <silent> $DETACH :call system(\"tmux detach -s $VRIM_ID\")"

if [ "$VRIM_SENDKEYS" = "1" ]; then
  REMAP="$REMAP<CR>"
  START_VIM_SERVER="vim -c '$REMAP' \"$@\""
else
  # note the <LT> workaround to prevent literal <CR>
  # being interpreted by --remote-silent
  REMAP="$REMAP<LT>CR>"

  # I haven't found a way to prevent vim from opening a [No Name] buffer first.
  # This deletes the first buffer.
  REMOVE_BLANK_BUFFER="bd1"

  START_VIM_SERVER="vim --servername $VRIM_ID --remote-silent +'$REMOVE_BLANK_BUFFER | $REMAP' \"$@\""
fi

# Check to see if tmux session is running
if ! tmux has-session -t $VRIM_ID >/dev/null 2>&1; then
  # Start vim server and containing tmux session
  REATTACH=$(which reattach-to-user-namespace)

  if [ -x "$REATTACH" ]; then
    START_VIM_SERVER="$REATTACH $START_VIM_SERVER"
  fi

  exec tmux -2 new-session -s $VRIM_ID "$START_VIM_SERVER" \; set status off \; >/dev/null 2>&1
else
  # Open requested file and attach to server
  if [ "$VRIM_SENDKEYS" = "1" ]; then
    tmux send-keys -t $VRIM_ID Escape
    tmux send-keys -t $VRIM_ID -l ":e $@"
    tmux send-keys -t $VRIM_ID Enter
  else
    vim --servername $VRIM_ID --remote "$@"
  fi
  exec tmux -2 attach -t $VRIM_ID >/dev/null 2>&1
fi
